### ISSUE TITLE
Plugin approval

### ISSUE THREAD

**Issue by NyakudyaA** [psigcat/ParCatGML#1]
# Problem

Please fix the Plugin home page link

Also, give a short description in English.

Explain plugin usefulness
@daviderill

**Comment by pcav** [comment]
Thanks for the description. Home page link still broken.
Thanks.

**Comment by pcav** [comment]
Now It is not broken, but it is very generic. Please replace it with one effectively describing the plugin. If nothing available, this repo would do.
Thanks.

**Comment by NyakudyaA** [comment]
@daviderill Still the homepage link doesn't refer to https://github.com/psigcat/ParCatGML

It just points to 
![pat](https://user-images.githubusercontent.com/2510900/67072153-8b816180-f184-11e9-809a-7437ef710244.png)

**Comment by daviderill** [comment]
@NyakudyaA Done. Thanks
