### ISSUE TITLE
The plugin doesn't work in the 3.10.4 QGIS version

### ISSUE THREAD

**Issue by dcastellvell** [psigcat/ParCatGML#3]
I recently uploaded QGIS from the 3.8 version to the latest LTR version (3.10.4) and I realised that in this latest version the plugin doesn't work. When I click on the button "Crear GML"  it frezze the program 

![Captura](https://user-images.githubusercontent.com/35541169/79354396-a454af00-7f3c-11ea-9e34-5407256939c2.PNG)

I 've checked in 3.8 with the same geometrys and works properly

**Comment by carlospsig** [comment]
Thanks, We're going to review it this week

**Comment by JordiGrasvi** [comment]
Hi, 
I use mac osx and I have the same problem, when running the QGIS plugin it gets blocked. I don't know how to debug the problem

**Comment by carlospsig** [comment]
We update this plugin a new version, 1.4, resolve this problem.
